[package]
name = "sw_galaxy_map_sync"
version = "0.3.2"
edition = "2024"
authors = ["Alessandro Maestri <umpire274@gmail.com>"]
description = "ArcGIS-first synchronization and ingestion tool for the Star Wars galaxy map and Astronavis datasets"
license = "MIT OR Apache-2.0"
repository = "https://github.com/umpire274/sw_galaxy_map"
homepage = "https://github.com/umpire274/sw_galaxy_map"
documentation = "https://github.com/umpire274/sw_galaxy_map"
readme = "README.md"
keywords = ["galaxy-map", "sync", "sqlite", "arcgis", "astronavis"]
categories = ["command-line-utilities"]

[dependencies]
anyhow.workspace = true
clap.workspace = true
csv.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
indicatif.workspace = true
regex.workspace = true
reqwest.workspace = true
sw_galaxy_map_core = { path = "../sw_galaxy_map_core" }

[lib]
name = "sw_galaxy_map_sync"
path = "src/lib.rs"

[[bin]]
name = "sw_galaxy_map_sync"
path = "src/main.rs"
